# Generated by Django 4.2.3 on 2023-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_tag_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
